In [47]:
 
from azure.identity import InteractiveBrowserCredential

cred = InteractiveBrowserCredential(tenant_id="8aefdf9f-8780-46bf-8fb7-4c924653a8be")

token = cred.get_token("https://storage.azure.com/.default")

print(token)

INFO Request URL: 'https://login.microsoftonline.com/8aefdf9f-8780-46bf-8fb7-4c924653a8be/v2.0/.well-known/openid-configuration'
Request method: 'GET'
Request headers:
    'User-Agent': 'azsdk-python-identity/1.25.1 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
No body was attached to the request
INFO Response status: 200
Response headers:
    'Cache-Control': 'max-age=86400, private'
    'Content-Type': 'application/json; charset=utf-8'
    'Strict-Transport-Security': 'REDACTED'
    'X-Content-Type-Options': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Access-Control-Allow-Methods': 'REDACTED'
    'P3P': 'REDACTED'
    'x-ms-request-id': '3a8d4e7a-f8da-411d-9dcd-1a0065000800'
    'x-ms-ests-server': 'REDACTED'
    'x-ms-srs': 'REDACTED'
    'Content-Security-Policy-Report-Only': 'REDACTED'
    'X-XSS-Protection': 'REDACTED'
    'Set-Cookie': 'REDACTED'
    'Date': 'Wed, 19 Nov 2025 16:19:40 GMT'
    'Content-Length': '1996'
INFO Request URL: 'https://login.microsoftonline.com/8aefdf9f-8780-46bf-8fb7-4c924653a8be/oauth2/v2.0/token'
Request method: 'POST'
Request headers:
    'Accept': 'application/json'
    'x-client-sku': 'REDACTED'
    'x-client-ver': 'REDACTED'
    'x-client-os': 'REDACTED'
    'x-ms-lib-capability': 'REDACTED'
    'client-request-id': 'REDACTED'
    'x-client-current-telemetry': 'REDACTED'
    'x-client-last-telemetry': 'REDACTED'
    'X-AnchorMailbox': 'REDACTED'
    'User-Agent': 'azsdk-python-identity/1.25.1 Python/3.11.5 (Windows-10-10.0.22631-SP0)'
A body is sent with the request
INFO Response status: 200
Response headers:
    'Cache-Control': 'no-store, no-cache'
    'Pragma': 'no-cache'
    'Content-Type': 'application/json; charset=utf-8'
    'Expires': '-1'
    'Strict-Transport-Security': 'REDACTED'
    'X-Content-Type-Options': 'REDACTED'
    'P3P': 'REDACTED'
    'client-request-id': 'REDACTED'
    'x-ms-request-id': 'ca6e3ec5-7665-4f8b-b498-e59578ab1500'
    'x-ms-ests-server': 'REDACTED'
    'x-ms-clitelem': 'REDACTED'
    'x-ms-srs': 'REDACTED'
    'Content-Security-Policy-Report-Only': 'REDACTED'
    'X-XSS-Protection': 'REDACTED'
    'Set-Cookie': 'REDACTED'
    'Date': 'Wed, 19 Nov 2025 16:19:45 GMT'
    'Content-Length': '7731'
INFO InteractiveBrowserCredential.get_token succeeded

AccessToken(token='eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6InJ0c0ZULWItN0x1WTdEVlllU05LY0lKN1ZuYyIsImtpZCI6InJ0c0ZULWItN0x1WTdEVlllU05LY0lKN1ZuYyJ9.eyJhdWQiOiJodHRwczovL3N0b3JhZ2UuYXp1cmUuY29tIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvOGFlZmRmOWYtODc4MC00NmJmLThmYjctNGM5MjQ2NTNhOGJlLyIsImlhdCI6MTc2MzU2ODg4NSwibmJmIjoxNzYzNTY4ODg1LCJleHAiOjE3NjM1NzM4MTIsImFjciI6IjEiLCJhaW8iOiJBVVFBdS84YUFBQUFIRFhqeDFVUElSUFpvb2UyUDBIbHJaVitlbWZzZGhlYkVtaHdUaEJseGt0UWFyOE9haGYwUTAzNG51VDFreVp5M2tqUnJtck9QNXQ0NXNNWGJBQzcwdz09IiwiYW1yIjpbInB3ZCIsInJzYSJdLCJhcHBpZCI6IjA0YjA3Nzk1LThkZGItNDYxYS1iYmVlLTAyZjllMWJmN2I0NiIsImFwcGlkYWNyIjoiMCIsImRldmljZWlkIjoiMjE1OWE4NGMtYjIyZC00NGMzLTgwNzktMDhlMGM2MjdlZWM4IiwiZmFtaWx5X25hbWUiOiJLaWFuaSIsImdpdmVuX25hbWUiOiJBbWlyaG9zc2VpbiIsImdyb3VwcyI6WyJiYzY1MzIwMC1jZjRlLTRkZTUtOGQwMS03NTEyNDIxOTMxMGMiLCI2MjNlMmUwYS1kMDE1LTQyYmMtODk5Yi1hNzYxNmM3OTQ0MjQiLCJjZjYxN2ExMC1lM2M0LTRlOTctOThlNi02NjZiMWYwMTkyOTEiLCJlM2ZmNGUxMS0xZmM0LTQxYTctYmNmOC1kMTJiMDAwYzRhZmYiLCIyOTdlMjUxMi1jMGQ4LTQyYmQtOWU5OS02Njg5YjA5YjZjZGMiLCI2MzA0MTUxYy0xYTEzLTQzMzItYmJjMi00ODFiODM4OTY4YTkiLCI2YTNmNjEyYy0zZDY2LTQ4M2QtOTFkZC1hYjYyYjAwZmM0M2MiLCI1NWNlZjczMi03MmI4LTRjNjItODNlZC04OGY2NDM3NmE1ZjEiLCJmYjZmNTMzOC1kODNlLTQ0NTAtYjA3Ni1kZGQxYWZjYzZlMGMiLCJkNjA4NjczOC1lMDdmLTQ1YWMtYjYzNS03MTlmZWYzZDMyYjMiLCIxZTRlYjUzOC1hZGEyLTRkODctYTA4My0xNjQ0YTY1NjM2MTMiLCJjNzBhN2YzZS1mZThmLTQyNzItOWM3OS03NTE5NGViMWZkOTQiLCJmNzRhOTYzZi1hMWVlLTQxNWUtODE4OC04NzhiN2EzNGMzYzYiLCI4YTYwMTE0ZC1jYTg1LTQ3YTAtOGQwOS1kYWQyYTU1ZGQwNmIiLCI5MTI3YTU1NC1iODczLTRjNWEtYTMzNC0yNDdhOWUxNWRiZDEiLCI4NjZjNzM1Ny0xMGRhLTRiZDctOWY0My0yNmFiY2M1Njc3MzAiLCJjZmNiN2M1OS1mMjliLTQ2MGEtOTZkNS04ZTZmMzk3YTg0NjYiLCI2OWE2YzY2NC1jMjY5LTQ0MDgtYWJmNS0zNTA3ZWQwY2IxZDYiLCJjMzYyNjg2ZC02YjhhLTRjZTAtOGNmMi1jMjhkMmQ4MGQwNWQiLCIzODcwNTc2Zi0wMTdmLTQ3MzEtYmQyMS0zYWM2ZGQ4M2Q5MmIiLCJmNWM4ODM2Zi1mYjlmLTQ1YTEtYTdhYy04ZWQzMmQ2NTYzOTMiLCJmNzc4Yzg2Zi0wYzRkLTQwMjctYWMzMC01NzlkODlmMDU3NzUiLCI5ZjFkMTA3NS1jZjE5LTQ1MDYtOGExZC03MGQzMjhmZjdmN2IiLCJjNDQxZDY3OS01NjQxLTQwMGUtODBjOS0xNWI0YjIzOTgyOWUiLCI4ZDIzODU3Yi00ZThmLTRhNDUtOGYyNi0wYzM0ZDcxY2EwMTEiLCI2YWZjN2M3ZS1hNWUzLTRmNGEtODlkMC1jYzdlMjk4MzY4NDYiLCJjNDI5OTI4Yy0yYjkzLTQ2ZmItOTVhMC1mMmY0MmQxMzFlMzgiLCI2NGQ1ZTA5NS03NWY4LTRhNjctYmQ1Mi01YmRhZmY3MzczZTEiLCI5YWYyZjI5ZC00YTU3LTQyMTYtYmMxMy03ODdlYWI3ZTM1NzQiLCI1M2ExYjJhNC04MDIzLTQ1OWUtYTQ2My1mMGRhYzJhYTJhMjAiLCIzMzRmM2ZhOC05N2M1LTQwNGUtODM0OC1iNzQ4MjFjMjA3MWIiLCIxODEwODRiNy1iMzM4LTRiOTYtYWM5YS1mOTg3MDMzZGVjYjEiLCIyODUxMDNiYi0yNGE1LTQ0NWMtYTVmMy1mYjUwNTIxOTQ1MzEiLCI0MWJkOGVkMS05M2U5LTQzNTAtYjNlMy1iODAyYWIxNmNjODQiLCJmOWM4ZjFkYy04YzFjLTQzNjItODA4My1kMDcwYmU2NDNjOGIiLCI5NmM3M2FlNy1iNjNlLTRlNjItYWM4Ny05Y2YyYjJlMDgyYzciLCJjMjhmNjdlOS0yOWZmLTQ2MGMtYmM2ZC0yZmZmOTg3NGUyOWQiLCIzZGJjOTFlYy0yZmJiLTQxZmQtYmFkMS1lNDI4MTFkOGMxYzQiLCI1YzEzMDZmMC02NmMxLTRmNjAtYjljYi1jYjQ5MDcxOTk3NTAiLCI1ZGJmZTdmNS1kZjJmLTQ3MDEtYjBhNi0yMjk4M2JhMTc3YmYiLCIyMTc0NTZmNy04Y2RhLTQ3N2UtYjFhMi1jMWJmY2I4MWM2ZDQiLCI2NGUzZmZmZi1iNmFlLTQ5NTMtODA2Yi1mYzJkMDAwZjk1MmQiXSwiaWR0eXAiOiJ1c2VyIiwiaXBhZGRyIjoiMTM3LjcwLjEyLjEwIiwibmFtZSI6IkFtaXJob3NzZWluIEtpYW5pIiwib2lkIjoiMmEyMWVkMmYtNmNhNy00OTk3LTkzZjYtMDRhYTlmZWU2M2EyIiwib25wcmVtX3NpZCI6IlMtMS01LTIxLTIxMzk0OTM1OTEtMjA3NjcyMzM5MS0xMTA1MTM4NzE2LTMxODM5NiIsInB1aWQiOiIxMDAzMjAwNEE3QzFFNjI3IiwicmgiOiIxLkFWc0FuOV92aW9DSHYwYVB0MHlTUmxPb3ZvR21CdVRVODZoQ2tMYkNzQ2xKZXZINUFJaGJBQS4iLCJzY3AiOiJ1c2VyX2ltcGVyc29uYXRpb24iLCJzaWQiOiIwMDlhYzE0OS0yMDBhLTU2MDQtNzQ4My03ZGYzMmJmOTc3Y2EiLCJzdWIiOiJyTjlkNnVQRk1BUE8yOHVya2tBZ3RXVk1LR1ZhcUc1QnE3cWVRNERRWU9nIiwidGlkIjoiOGFlZmRmOWYtODc4MC00NmJmLThmYjctNGM5MjQ2NTNhOGJlIiwidW5pcXVlX25hbWUiOiJBbWlyaG9zc2Vpbi5LaWFuaUBoZW5uZXBpbi51cyIsInVwbiI6IkFtaXJob3NzZWluLktpYW5pQGhlbm5lcGluLnVzIiwidXRpIjoieFQ1dXltVjJpMC0wbU9XVmVLc1ZBQSIsInZlciI6IjEuMCIsInhtc19hY3RfZmN0IjoiMyA1IiwieG1zX2Z0ZCI6IlN4YVFiWURXczNQVDY2azFIZ2Q0UXJ0QmdQeDJ6TXRtNkZiTjRkc2h1dmtCZFhOemIzVjBhQzFrYzIxeiIsInhtc19pZHJlbCI6IjEgOCIsInhtc19zdWJfZmN0IjoiMyA4In0.X04v6_C_yufnYAGKZz8eMWG2Qa8RHjj0YYX-KQBoe5Kt_-CP7aa1SsGv_O_CLGGXGgRhSS9jRG_eY4ffEcBsL8fLTqYReOZ5-umnWuRAApBJtmaDiDxbuIVz-IwJwktxrNvgx1XTVD-xUYXQ4g7HWWAIhyM17TcQBLE-M7W2yoRKPuc7U-tTFwAxyQozO2xPLL8nGGoCIkhU8OYn97UMjKUGd0IzXlcZdfe_Y8ZK04j-E0pL6iX8tzk-ASUqzS7oGaVE1CueJ5zspyJFzOUrxl_-B-NmzYxOeQ-2Uv3g-WNdKGt0zRk2BSdkMzNVcNS66S2yycoaY3Z4wxnuL3uAVg', expires_on=1763573807)

# Fusing the detection vehicles info

In [1]:
from pathlib import Path
import sys
import os
import django
from django.conf import settings


project_root = Path(r".\backend")
sys.path.insert(0, str(project_root))

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "backend.processor.settings")

django.setup()

print("Loaded settings module:", os.environ.get("DJANGO_SETTINGS_MODULE"))
print("DATABASES:", settings.DATABASES)

Loaded settings module: backend.processor.settings
DATABASES: {'default': {'ENGINE': 'django.db.backends.sqlite3', 'NAME': WindowsPath('C:/MyApps/VisionSaver/backend/db.sqlite3'), 'TEST': {'MIRROR': 'default', 'CHARSET': None, 'COLLATION': None, 'MIGRATE': True, 'NAME': None}, 'ATOMIC_REQUESTS': False, 'AUTOCOMMIT': True, 'CONN_MAX_AGE': 0, 'CONN_HEALTH_CHECKS': False, 'OPTIONS': {}, 'TIME_ZONE': None, 'USER': '', 'PASSWORD': '', 'HOST': '', 'PORT': ''}}

In [50]:
from record.models import Record, RecordLog # type: ignore
from ai.models import AutoDetection, DetectionLines # type: ignore
from asgiref.sync import sync_to_async

detections = await sync_to_async(list)(AutoDetection.objects.all())

In [131]:
import pandas as pd
movement_to_keys = {"through": 10, "left": 20, "right": 30}


def get_auto_detection_movements(auto_df, lines, record_id):
    min_max = auto_df.groupby("track_id")["time"].agg({"min", "max"})
    min_max["diff"] = min_max["max"] - min_max["min"]
    zone_numbers = {key:len(value) for key, value in lines.items()}
    significant_tracks = min_max[min_max["diff"] > 1].index.tolist()
    significant_auto_df = auto_df[auto_df["track_id"].isin(significant_tracks)]
    automobile_cls_ids = [2, 5, 7]
    significant_auto_df_vehicles = significant_auto_df[significant_auto_df["cls_id"].isin(automobile_cls_ids)]
    significant_auto_df_vehicles["line_index_key"] = significant_auto_df_vehicles["line_index"].apply(
        lambda x: next((movement_to_keys[k] for k in movement_to_keys if k in str(x).lower()), None)
    )
    significant_auto_df_vehicles = significant_auto_df_vehicles.dropna(subset=["line_index_key"])
    significant_auto_df_vehicles["final_turn_movement"] = None
    groups = significant_auto_df_vehicles.groupby("track_id")[["time", "line_index_key", "zone_index"]]
    for track_id, group in groups:
        subgroups = {
            line_key: list(int(z) for z in sub["zone_index"].unique())
            for line_key, sub in group.groupby("line_index_key")
        }
        zone_numbers_mapped = {}
        for line_name, zones_list in lines.items():
            mapped_key = next(
            (movement_to_keys[k] for k in movement_to_keys if k in str(line_name).lower()),
            None,
            )
            if mapped_key is not None:
                zone_numbers_mapped[mapped_key] = len(zones_list)
        
        # replace the string-keyed zone_numbers with numeric-keyed mapping so subsequent checks work
        zone_numbers = zone_numbers_mapped
        for line_key, zones in subgroups.items():
            if len(zones) == zone_numbers.get(line_key, 0):
                # check if zones is incremental, if not we are not interested
                
                if zones == sorted(zones):
                    
                    significant_auto_df_vehicles.loc[significant_auto_df_vehicles["track_id"] == track_id, "final_turn_movement"] = line_key
                    # TODO: we might need to check this value against other line keys. This
                    # might not be the end of the process. Check this later
                    break
    
    significant_auto_df_vehicles.dropna(subset=["final_turn_movement"], inplace=True)
    significant_auto_df_vehicles["record_id"] = record_id
    return significant_auto_df_vehicles

def get_matching_data(manaul_df, auto_df, auto_lines, record_id):
    significant_auto_df_vehicles = get_auto_detection_movements(auto_df, auto_lines, record_id)
    significant_auto_df_vehicles["matched"] = False
    manual_df_temp = manaul_df.copy()
    manual_df_temp["line_index_key"] = manual_df_temp["turn_movement"].apply(
        lambda x: movement_to_keys.get(str(x).lower(), None)
    )
    manual_df_temp["matched"] = False
    detection_time_df = significant_auto_df_vehicles.groupby(["track_id", "final_turn_movement"]).agg({"time": "max"}).rename({"time": "detection_time"}, axis=1).reset_index()
    for index, row in detection_time_df.iterrows():
        track_id = row["track_id"]
        final_turn_movement = row["final_turn_movement"]
        detection_time = row["detection_time"]
        time_window_start = detection_time - 5  # 2 seconds before
        time_window_end = detection_time + 5    # 2 seconds after
        mask = (
            (manual_df_temp["line_index_key"] == final_turn_movement) &
            (manual_df_temp["time"] >= time_window_start) &
            (manual_df_temp["time"] <= time_window_end) &
            (~manual_df_temp["matched"])
        )
        matched_indices = manual_df_temp[mask].index
        manual_df_temp.loc[matched_indices, "matched"] = True
        significant_auto_df_vehicles.loc[significant_auto_df_vehicles["track_id"] == track_id, "matched"] = True
    return significant_auto_df_vehicles

In [132]:
from tqdm import tqdm
final_df = pd.DataFrame()
starting_number = 1
for detection in tqdm(detections):
    record_id = detection.record_id
    record = await sync_to_async(list)(Record.objects.filter(id=record_id))
    if record:
        record = record[0]
        if record.finished_detecting:
            record_manual_logs = await sync_to_async(list)(RecordLog.objects.filter(record_id=record_id))
            record_manual_df_dict = {"time":[], "turn_movement":[], "record_id": []}

            for log in record_manual_logs:
                record_manual_df_dict["time"].append(log.time)
                record_manual_df_dict["turn_movement"].append(log.turn_movement)
                record_manual_df_dict["record_id"].append(record_id)
            record_manual_df = pd.DataFrame(record_manual_df_dict)
            detection_auto_df = pd.read_csv(detection.file_name)
            detection_lines = await sync_to_async(list)(DetectionLines.objects.filter(record_id=record_id))
            auto_lines = detection_lines[0].lines
            matching_data = get_matching_data(record_manual_df, detection_auto_df, auto_lines, record_id)
            # Remap track_id
            unique_track_ids = sorted(matching_data["track_id"].unique())
            track_id_map = {old_id: new_id for new_id, old_id in enumerate(unique_track_ids, start=starting_number)}
            matching_data.loc[:, "track_id"] = matching_data["track_id"].map(track_id_map)
            starting_number += len(unique_track_ids) + 1
            final_df = pd.concat([final_df, matching_data], ignore_index=True)

  3%|▎         | 4/115 [00:00<00:14,  7.90it/s]C:\Users\amki003\AppData\Local\Temp\ipykernel_28996\252472832.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  significant_auto_df_vehicles["line_index_key"] = significant_auto_df_vehicles["line_index"].apply(
  9%|▊         | 10/115 [00:01<00:14,  7.40it/s]C:\Users\amki003\AppData\Local\Temp\ipykernel_28996\252472832.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  significant_auto_df_vehicles["line_index_key"] = significant_auto_df_vehicles["line_index"].apply(
 10%|▉         | 11/115 [00:01<00:14,  7.12it/s]C:\Users\amki003\AppData\Local\Temp\ipykernel_28996\252472832.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  significant_auto_df_vehicles["line_index_key"] = significant_auto_df_vehicles["line_index"].apply(
C:\Users\amki003\AppData\Local\Temp\ipykernel_28996\252472832.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  significant_auto_df_vehicles["line_index_key"] = significant_auto_df_vehicles["line_index"].apply(
 16%|█▌        | 18/115 [00:03<00:22,  4.41it/s]C:\Users\amki003\AppData\Local\Temp\ipykernel_28996\252472832.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  significant_auto_df_vehicles["line_index_key"] = significant_auto_df_vehicles["line_index"].apply(
 20%|██        | 23/115 [00:04<00:29,  3.08it/s]C:\Users\amki003\AppData\Local\Temp\ipykernel_28996\252472832.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  significant_auto_df_vehicles["line_index_key"] = significant_auto_df_vehicles["line_index"].apply(
 28%|██▊       | 32/115 [00:09<00:39,  2.11it/s]C:\Users\amki003\AppData\Local\Temp\ipykernel_28996\252472832.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  significant_auto_df_vehicles["line_index_key"] = significant_auto_df_vehicles["line_index"].apply(
 29%|██▊       | 33/115 [00:10<00:42,  1.91it/s]C:\Users\amki003\AppData\Local\Temp\ipykernel_28996\252472832.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  significant_auto_df_vehicles["line_index_key"] = significant_auto_df_vehicles["line_index"].apply(
 38%|███▊      | 44/115 [00:14<00:15,  4.45it/s]C:\Users\amki003\AppData\Local\Temp\ipykernel_28996\252472832.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  significant_auto_df_vehicles["line_index_key"] = significant_auto_df_vehicles["line_index"].apply(
 45%|████▌     | 52/115 [00:15<00:10,  5.84it/s]C:\Users\amki003\AppData\Local\Temp\ipykernel_28996\252472832.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  significant_auto_df_vehicles["line_index_key"] = significant_auto_df_vehicles["line_index"].apply(
 47%|████▋     | 54/115 [00:15<00:10,  5.78it/s]C:\Users\amki003\AppData\Local\Temp\ipykernel_28996\252472832.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  significant_auto_df_vehicles["line_index_key"] = significant_auto_df_vehicles["line_index"].apply(
 50%|█████     | 58/115 [00:16<00:07,  7.28it/s]C:\Users\amki003\AppData\Local\Temp\ipykernel_28996\252472832.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  significant_auto_df_vehicles["line_index_key"] = significant_auto_df_vehicles["line_index"].apply(
C:\Users\amki003\AppData\Local\Temp\ipykernel_28996\252472832.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  significant_auto_df_vehicles["line_index_key"] = significant_auto_df_vehicles["line_index"].apply(
 52%|█████▏    | 60/115 [00:16<00:06,  7.96it/s]C:\Users\amki003\AppData\Local\Temp\ipykernel_28996\252472832.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  significant_auto_df_vehicles["line_index_key"] = significant_auto_df_vehicles["line_index"].apply(
 54%|█████▍    | 62/115 [00:16<00:07,  7.39it/s]C:\Users\amki003\AppData\Local\Temp\ipykernel_28996\252472832.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  significant_auto_df_vehicles["line_index_key"] = significant_auto_df_vehicles["line_index"].apply(
 63%|██████▎   | 72/115 [00:19<00:11,  3.83it/s]C:\Users\amki003\AppData\Local\Temp\ipykernel_28996\252472832.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  significant_auto_df_vehicles["line_index_key"] = significant_auto_df_vehicles["line_index"].apply(
 64%|██████▍   | 74/115 [00:20<00:17,  2.33it/s]C:\Users\amki003\AppData\Local\Temp\ipykernel_28996\252472832.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  significant_auto_df_vehicles["line_index_key"] = significant_auto_df_vehicles["line_index"].apply(
 71%|███████▏  | 82/115 [00:25<00:17,  1.84it/s]C:\Users\amki003\AppData\Local\Temp\ipykernel_28996\252472832.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  significant_auto_df_vehicles["line_index_key"] = significant_auto_df_vehicles["line_index"].apply(
 77%|███████▋  | 89/115 [00:29<00:14,  1.79it/s]C:\Users\amki003\AppData\Local\Temp\ipykernel_28996\2213961832.py:27: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  final_df = pd.concat([final_df, matching_data], ignore_index=True)
 81%|████████  | 93/115 [00:31<00:09,  2.33it/s]C:\Users\amki003\AppData\Local\Temp\ipykernel_28996\252472832.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  significant_auto_df_vehicles["line_index_key"] = significant_auto_df_vehicles["line_index"].apply(
 87%|████████▋ | 100/115 [00:33<00:05,  2.56it/s]C:\Users\amki003\AppData\Local\Temp\ipykernel_28996\252472832.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  significant_auto_df_vehicles["line_index_key"] = significant_auto_df_vehicles["line_index"].apply(
 93%|█████████▎| 107/115 [00:35<00:02,  3.42it/s]C:\Users\amki003\AppData\Local\Temp\ipykernel_28996\252472832.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  significant_auto_df_vehicles["line_index_key"] = significant_auto_df_vehicles["line_index"].apply(
100%|██████████| 115/115 [00:38<00:00,  2.99it/s]

In [133]:
final_df.to_csv("vehicle_movements.csv", index=False)

In [134]:
final_df

,track_id,x1,y1,x2,y2,cls_id,confidence,time,in_area,line_index,zone_index,line_index_key,final_turn_movement,record_id,matched
0,1,0.435003,0.221162,0.499184,0.322312,2,0.811245,0.066733,True,through,0,10.0,10.0,90,True
1,2,0.512382,0.363224,0.606207,0.552886,2,0.477426,0.066733,True,through,0,10.0,10.0,90,True
2,3,0.556482,0.098199,0.590168,0.145772,2,0.365922,0.066733,True,through,0,10.0,10.0,90,True
3,1,0.434532,0.221814,0.498774,0.323175,2,0.792563,0.100100,True,through,0,10.0,10.0,90,True
4,2,0.512257,0.363086,0.606152,0.552892,2,0.470074,0.100100,True,through,0,10.0,10.0,90,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3140251,10510,0.360873,0.432363,0.479815,0.680138,2,0.748573,893.422000,True,through,0,10.0,10.0,221,True
3140252,10510,0.357074,0.442372,0.479543,0.698436,2,0.813484,893.455000,True,through,0,10.0,10.0,221,True
3140253,10510,0.352698,0.454708,0.478715,0.719037,2,0.769498,893.489000,True,through,0,10.0,10.0,221,True
3140254,10510,0.291467,0.649023,0.453555,1.004230,2,0.476249,893.889000,True,through,1,10.0,10.0,221,True
3140255,10510,0.287430,0.663097,0.451630,1.022970,2,0.476249,893.922000,True,through,1,10.0,10.0,221,True

In [4]:
from django.conf import settings
import os
import cv2
from asgiref.sync import sync_to_async
from record.models import Record # type: ignore
media_root = settings.MEDIA_ROOT
records = await sync_to_async(list)(Record.objects.all())
video_data = {"record_id": [], "width": [], "height": []}
for record in records:
    record_id = record.id
    file_path = os.path.join(media_root, f"{record_id}.mkv")
    if not os.path.exists(file_path):
        file_path = os.path.join(media_root, f"{record_id}.mp4")
        if not os.path.exists(file_path):
            continue
    
    # Get video height and width
    cap = cv2.VideoCapture(file_path)
    if not cap.isOpened():
        print(f"Failed to open video file: {file_path}")
        continue
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    video_data["record_id"].append(record_id)
    video_data["width"].append(width)
    video_data["height"].append(height)

import pandas as pd
video_df = pd.DataFrame(video_data)
video_df.to_csv("video_dimensions.csv", index=False)

# Load videos movements and video dimensions

In [1]:
import pandas as pd
final_df = pd.read_csv("vehicle_movements.csv")
video_df = pd.read_csv("video_dimensions.csv")

In [2]:
final_df

,track_id,x1,y1,x2,y2,cls_id,confidence,time,in_area,line_index,zone_index,line_index_key,final_turn_movement,record_id,matched
0,1,0.435003,0.221162,0.499184,0.322312,2,0.811245,0.066733,True,through,0,10.0,10.0,90,True
1,2,0.512382,0.363224,0.606207,0.552886,2,0.477426,0.066733,True,through,0,10.0,10.0,90,True
2,3,0.556482,0.098199,0.590168,0.145772,2,0.365922,0.066733,True,through,0,10.0,10.0,90,True
3,1,0.434532,0.221814,0.498774,0.323175,2,0.792563,0.100100,True,through,0,10.0,10.0,90,True
4,2,0.512257,0.363086,0.606152,0.552892,2,0.470074,0.100100,True,through,0,10.0,10.0,90,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3140251,10510,0.360873,0.432363,0.479815,0.680138,2,0.748573,893.422000,True,through,0,10.0,10.0,221,True
3140252,10510,0.357074,0.442372,0.479543,0.698436,2,0.813484,893.455000,True,through,0,10.0,10.0,221,True
3140253,10510,0.352698,0.454708,0.478715,0.719037,2,0.769498,893.489000,True,through,0,10.0,10.0,221,True
3140254,10510,0.291467,0.649023,0.453555,1.004230,2,0.476249,893.889000,True,through,1,10.0,10.0,221,True
3140255,10510,0.287430,0.663097,0.451630,1.022970,2,0.476249,893.922000,True,through,1,10.0,10.0,221,True

# Augment data

In [4]:
from tqdm import tqdm
temp_df = final_df.copy()
groups = temp_df.groupby("record_id")
augment_size = 10
max_record_id = temp_df["record_id"].max()
import numpy as np
def rotate_point(x, y, cx, cy, angle_rad):
    cos_angle = np.cos(angle_rad)
    sin_angle = np.sin(angle_rad)
    x_new = cos_angle * (x - cx) - sin_angle * (y - cy) + cx
    y_new = sin_angle * (x - cx) + cos_angle * (y - cy) + cy
    return x_new, y_new
for record_id, group in tqdm(groups, total=len(groups)):
    copied_group = group.copy()
    x1, y1, x2, y2 = copied_group["x1"].values, copied_group["y1"].values, copied_group["x2"].values, copied_group["y2"].values
    for i in range(1, augment_size + 1):
        max_record_id += 1
        # Get random rotation angle between -pi and pi
        angle_rad = np.random.uniform(-np.pi/2, 0)
        # video_info = video_df[video_df["record_id"] == record_id]
        # if video_info.empty:
        #     continue
        new_x_1, new_y_1 = rotate_point(x1, y1, 0, 0, angle_rad)
        new_x_2, new_y_2 = rotate_point(x2, y2, 0, 0, angle_rad)
        augmented_group = copied_group.copy()
        augmented_group["x1"] = new_x_1
        augmented_group["y1"] = new_y_1
        augmented_group["x2"] = new_x_2
        augmented_group["y2"] = new_y_2
        augmented_group["record_id"] = max_record_id
        temp_df = pd.concat([temp_df, augmented_group], ignore_index=True)
temp_df.to_csv("augmented_vehicle_movements.csv", index=False)

100%|██████████| 71/71 [07:43<00:00,  6.52s/it]

In [ ]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset
class TurnMovementClassifier(nn.Module):
    def __init__(self, num_classes):
        super().__init__()
        self.mlp = nn.Sequential(
            nn.Linear(3, 32),
            nn.ReLU(),
            nn.Linear(32, 32),
            nn.ReLU(),
            nn.Linear(32, num_classes)
        )

    def forward(self, x):
        return self.mlp(x)
    
class TurnMovementDataset(Dataset):
    def __init__(self, features, labels):
        self.features = features
        self.labels = labels

    def __len__(self):
        return len(self.features)

    def __getitem__(self, idx):
        return self.features[idx], self.labels[idx]

SyntaxError: incomplete input (2019922348.py, line 19)

In [ ]:
model = TurnMovementClassifier(num_classes=3)
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
loss_fn = nn.CrossEntropyLoss()
df = pd.read_csv("augmented_vehicle_movements.csv")

In [ ]:

turn_movement_map = {10: 0, 20: 1, 30: 2}  # through:0, left:1, right:2
from torch.utils.data import DataLoader
all_record_metrics = {}
EPOCHS_PER_RECORD = 5
for record_id, record_group in df.groupby("record_id"):

    print(f"\n==============================")
    print(f" Training on record {record_id} ")
    print(f"==============================\n")

    features_list = []
    labels_list = []

    for track_id, track_group in record_group.groupby("track_id"):

        track_group = track_group.sort_values("time")

        x_c = ((track_group["x1"] + track_group["x2"]) / 2).values
        y_c = ((track_group["y1"] + track_group["y2"]) / 2).values

        dx = np.diff(x_c, prepend=x_c[0])
        dy = np.diff(y_c, prepend=y_c[0])

        start_heading = np.arctan2(dy[0], dx[0])
        end_heading   = np.arctan2(dy[-1], dx[-1])

        delta = np.arctan2(np.sin(end_heading - start_heading),
                           np.cos(end_heading - start_heading))

        final_x = x_c[-1]
        final_y = y_c[-1]

        feature_vec = torch.tensor([delta, final_x, final_y], dtype=torch.float32)

        label = turn_movement_map[track_group["final_turn_movement"].iloc[0]]

        features_list.append(feature_vec)
        labels_list.append(label)

    # dataset
    dataset = TurnMovementDataset(features_list, labels_list)
    dataloader = DataLoader(dataset, batch_size=32, shuffle=True)

    # Train & evaluate metrics
    epoch_losses = []
    epoch_accuracies = []

    for epoch in range(EPOCHS_PER_RECORD):
        model.train()
        total_loss = 0
        correct = 0
        total = 0

        for batch_features, batch_labels in dataloader:
            batch_labels = batch_labels.long()

            optimizer.zero_grad()
            logits = model(batch_features)
            loss = loss_fn(logits, batch_labels)
            loss.backward()
            optimizer.step()

            total_loss += loss.item() * batch_features.size(0)

            preds = torch.argmax(logits, dim=1)
            correct += (preds == batch_labels).sum().item()
            total += batch_labels.size(0)

        avg_loss = total_loss / total
        accuracy = correct / total

        epoch_losses.append(avg_loss)
        epoch_accuracies.append(accuracy)

        print(f"Record {record_id} | Epoch {epoch+1}/{EPOCHS_PER_RECORD} | "
              f"Loss: {avg_loss:.4f} | Accuracy: {accuracy:.3f}")

    # Save metrics
    all_record_metrics[record_id] = {
        "losses": epoch_losses,
        "accuracies": epoch_accuracies
    }

    # SAVE MODEL AFTER EACH RECORD
    torch.save(model.state_dict(), f"turn_movement_model_latest.pth")
    print(f"Model saved after record {record_id}.")

Creating the dataset for record: 19
Training on record 19, epoch 1/5
Training on record 19, epoch 2/5
Training on record 19, epoch 3/5
Training on record 19, epoch 4/5
Training on record 19, epoch 5/5
Creating the dataset for record: 20
Training on record 20, epoch 1/5
Training on record 20, epoch 2/5
Training on record 20, epoch 3/5
Training on record 20, epoch 4/5
Training on record 20, epoch 5/5
Creating the dataset for record: 21
Training on record 21, epoch 1/5
Training on record 21, epoch 2/5
Training on record 21, epoch 3/5
Training on record 21, epoch 4/5
Training on record 21, epoch 5/5
Creating the dataset for record: 22
Training on record 22, epoch 1/5
Training on record 22, epoch 2/5
Training on record 22, epoch 3/5
Training on record 22, epoch 4/5
Training on record 22, epoch 5/5
Creating the dataset for record: 88
Training on record 88, epoch 1/5
Training on record 88, epoch 2/5
Training on record 88, epoch 3/5
Training on record 88, epoch 4/5
Training on record 88, epoch 5/5
Creating the dataset for record: 89
Training on record 89, epoch 1/5
Training on record 89, epoch 2/5
Training on record 89, epoch 3/5
Training on record 89, epoch 4/5
Training on record 89, epoch 5/5
Creating the dataset for record: 90
Training on record 90, epoch 1/5
Training on record 90, epoch 2/5
Training on record 90, epoch 3/5
Training on record 90, epoch 4/5
Training on record 90, epoch 5/5
Creating the dataset for record: 91
Training on record 91, epoch 1/5
Training on record 91, epoch 2/5
Training on record 91, epoch 3/5
Training on record 91, epoch 4/5
Training on record 91, epoch 5/5
Creating the dataset for record: 92
Training on record 92, epoch 1/5
Training on record 92, epoch 2/5
Training on record 92, epoch 3/5
Training on record 92, epoch 4/5
Training on record 92, epoch 5/5
Creating the dataset for record: 93
Training on record 93, epoch 1/5
Training on record 93, epoch 2/5
Training on record 93, epoch 3/5
Training on record 93, epoch 4/5
Training on record 93, epoch 5/5
Creating the dataset for record: 94
Training on record 94, epoch 1/5
Training on record 94, epoch 2/5
Training on record 94, epoch 3/5
Training on record 94, epoch 4/5
Training on record 94, epoch 5/5
Creating the dataset for record: 95
Training on record 95, epoch 1/5
Training on record 95, epoch 2/5
Training on record 95, epoch 3/5
Training on record 95, epoch 4/5
Training on record 95, epoch 5/5
Creating the dataset for record: 96
Training on record 96, epoch 1/5
Training on record 96, epoch 2/5
Training on record 96, epoch 3/5
Training on record 96, epoch 4/5
Training on record 96, epoch 5/5
Creating the dataset for record: 97
Training on record 97, epoch 1/5
Training on record 97, epoch 2/5
Training on record 97, epoch 3/5
Training on record 97, epoch 4/5
Training on record 97, epoch 5/5
Creating the dataset for record: 98
Training on record 98, epoch 1/5
Training on record 98, epoch 2/5
Training on record 98, epoch 3/5
Training on record 98, epoch 4/5
Training on record 98, epoch 5/5
Creating the dataset for record: 99
Training on record 99, epoch 1/5
Training on record 99, epoch 2/5
Training on record 99, epoch 3/5
Training on record 99, epoch 4/5
Training on record 99, epoch 5/5
Creating the dataset for record: 104
Training on record 104, epoch 1/5
Training on record 104, epoch 2/5
Training on record 104, epoch 3/5
Training on record 104, epoch 4/5
Training on record 104, epoch 5/5
Creating the dataset for record: 105
Training on record 105, epoch 1/5
Training on record 105, epoch 2/5
Training on record 105, epoch 3/5
Training on record 105, epoch 4/5
Training on record 105, epoch 5/5
Creating the dataset for record: 106
Training on record 106, epoch 1/5
Training on record 106, epoch 2/5
Training on record 106, epoch 3/5
Training on record 106, epoch 4/5
Training on record 106, epoch 5/5
Creating the dataset for record: 107
Training on record 107, epoch 1/5
Training on record 107, epoch 2/5
Training on record 107, epoch 3/5
Training on record 107, epoch 4/5
Training on record 107, epoch 5/5
Creating the dataset for record: 121
Training on record 121, epoch 1/5
Training on record 121, epoch 2/5
Training on record 121, epoch 3/5
Training on record 121, epoch 4/5
Training on record 121, epoch 5/5
Creating the dataset for record: 122
Training on record 122, epoch 1/5
Training on record 122, epoch 2/5
Training on record 122, epoch 3/5
Training on record 122, epoch 4/5
Training on record 122, epoch 5/5
Creating the dataset for record: 123
Training on record 123, epoch 1/5
Training on record 123, epoch 2/5
Training on record 123, epoch 3/5
Training on record 123, epoch 4/5
Training on record 123, epoch 5/5
Creating the dataset for record: 124
Training on record 124, epoch 1/5
Training on record 124, epoch 2/5
Training on record 124, epoch 3/5
Training on record 124, epoch 4/5
Training on record 124, epoch 5/5
Creating the dataset for record: 125
Training on record 125, epoch 1/5
Training on record 125, epoch 2/5
Training on record 125, epoch 3/5
Training on record 125, epoch 4/5
Training on record 125, epoch 5/5
Creating the dataset for record: 126
Training on record 126, epoch 1/5
Training on record 126, epoch 2/5
Training on record 126, epoch 3/5
Training on record 126, epoch 4/5
Training on record 126, epoch 5/5
Creating the dataset for record: 127
Training on record 127, epoch 1/5
Training on record 127, epoch 2/5
Training on record 127, epoch 3/5
Training on record 127, epoch 4/5
Training on record 127, epoch 5/5
Creating the dataset for record: 128
Training on record 128, epoch 1/5
Training on record 128, epoch 2/5
Training on record 128, epoch 3/5
Training on record 128, epoch 4/5
Training on record 128, epoch 5/5
Creating the dataset for record: 130
Training on record 130, epoch 1/5
Training on record 130, epoch 2/5
Training on record 130, epoch 3/5
Training on record 130, epoch 4/5
Training on record 130, epoch 5/5
Creating the dataset for record: 131
Training on record 131, epoch 1/5
Training on record 131, epoch 2/5
Training on record 131, epoch 3/5
Training on record 131, epoch 4/5
Training on record 131, epoch 5/5
Creating the dataset for record: 132
Training on record 132, epoch 1/5
Training on record 132, epoch 2/5
Training on record 132, epoch 3/5
Training on record 132, epoch 4/5
Training on record 132, epoch 5/5
Creating the dataset for record: 133
Training on record 133, epoch 1/5
Training on record 133, epoch 2/5
Training on record 133, epoch 3/5
Training on record 133, epoch 4/5
Training on record 133, epoch 5/5
Creating the dataset for record: 134
Training on record 134, epoch 1/5
Training on record 134, epoch 2/5
Training on record 134, epoch 3/5
Training on record 134, epoch 4/5
Training on record 134, epoch 5/5
Creating the dataset for record: 139
Training on record 139, epoch 1/5
Training on record 139, epoch 2/5
Training on record 139, epoch 3/5
Training on record 139, epoch 4/5
Training on record 139, epoch 5/5
Creating the dataset for record: 140
Training on record 140, epoch 1/5
Training on record 140, epoch 2/5
Training on record 140, epoch 3/5
Training on record 140, epoch 4/5
Training on record 140, epoch 5/5
Creating the dataset for record: 141
Training on record 141, epoch 1/5
Training on record 141, epoch 2/5
Training on record 141, epoch 3/5
Training on record 141, epoch 4/5
Training on record 141, epoch 5/5
Creating the dataset for record: 142
Training on record 142, epoch 1/5
Training on record 142, epoch 2/5
Training on record 142, epoch 3/5
Training on record 142, epoch 4/5
Training on record 142, epoch 5/5
Creating the dataset for record: 143
Training on record 143, epoch 1/5
Training on record 143, epoch 2/5
Training on record 143, epoch 3/5
Training on record 143, epoch 4/5
Training on record 143, epoch 5/5
Creating the dataset for record: 144
Training on record 144, epoch 1/5
Training on record 144, epoch 2/5
Training on record 144, epoch 3/5
Training on record 144, epoch 4/5
Training on record 144, epoch 5/5
Creating the dataset for record: 146
Training on record 146, epoch 1/5
Training on record 146, epoch 2/5
Training on record 146, epoch 3/5
Training on record 146, epoch 4/5
Training on record 146, epoch 5/5
Creating the dataset for record: 147
Training on record 147, epoch 1/5
Training on record 147, epoch 2/5
Training on record 147, epoch 3/5
Training on record 147, epoch 4/5
Training on record 147, epoch 5/5
Creating the dataset for record: 148
Training on record 148, epoch 1/5
Training on record 148, epoch 2/5
Training on record 148, epoch 3/5
Training on record 148, epoch 4/5
Training on record 148, epoch 5/5
Creating the dataset for record: 149
Training on record 149, epoch 1/5
Training on record 149, epoch 2/5
Training on record 149, epoch 3/5
Training on record 149, epoch 4/5
Training on record 149, epoch 5/5
Creating the dataset for record: 150
Training on record 150, epoch 1/5
Training on record 150, epoch 2/5
Training on record 150, epoch 3/5
Training on record 150, epoch 4/5
Training on record 150, epoch 5/5
Creating the dataset for record: 151
Training on record 151, epoch 1/5
Training on record 151, epoch 2/5
Training on record 151, epoch 3/5
Training on record 151, epoch 4/5
Training on record 151, epoch 5/5
Creating the dataset for record: 152
Training on record 152, epoch 1/5
Training on record 152, epoch 2/5
Training on record 152, epoch 3/5
Training on record 152, epoch 4/5
Training on record 152, epoch 5/5
Creating the dataset for record: 153
Training on record 153, epoch 1/5
Training on record 153, epoch 2/5
Training on record 153, epoch 3/5
Training on record 153, epoch 4/5
Training on record 153, epoch 5/5
Creating the dataset for record: 154
Training on record 154, epoch 1/5
Training on record 154, epoch 2/5
Training on record 154, epoch 3/5
Training on record 154, epoch 4/5
Training on record 154, epoch 5/5
Creating the dataset for record: 158
Training on record 158, epoch 1/5
Training on record 158, epoch 2/5
Training on record 158, epoch 3/5
Training on record 158, epoch 4/5
Training on record 158, epoch 5/5
Creating the dataset for record: 159
Training on record 159, epoch 1/5
Training on record 159, epoch 2/5
Training on record 159, epoch 3/5
Training on record 159, epoch 4/5
Training on record 159, epoch 5/5
Creating the dataset for record: 160
Training on record 160, epoch 1/5
Training on record 160, epoch 2/5
Training on record 160, epoch 3/5
Training on record 160, epoch 4/5
Training on record 160, epoch 5/5
Creating the dataset for record: 161
Training on record 161, epoch 1/5
Training on record 161, epoch 2/5
Training on record 161, epoch 3/5
Training on record 161, epoch 4/5
Training on record 161, epoch 5/5
Creating the dataset for record: 170
Training on record 170, epoch 1/5
Training on record 170, epoch 2/5
Training on record 170, epoch 3/5
Training on record 170, epoch 4/5
Training on record 170, epoch 5/5
Creating the dataset for record: 171
Training on record 171, epoch 1/5
Training on record 171, epoch 2/5
Training on record 171, epoch 3/5
Training on record 171, epoch 4/5
Training on record 171, epoch 5/5
Creating the dataset for record: 172
Training on record 172, epoch 1/5
Training on record 172, epoch 2/5
Training on record 172, epoch 3/5
Training on record 172, epoch 4/5
Training on record 172, epoch 5/5
Creating the dataset for record: 184
Training on record 184, epoch 1/5
Training on record 184, epoch 2/5
Training on record 184, epoch 3/5
Training on record 184, epoch 4/5
Training on record 184, epoch 5/5
Creating the dataset for record: 185
Training on record 185, epoch 1/5
Training on record 185, epoch 2/5
Training on record 185, epoch 3/5
Training on record 185, epoch 4/5
Training on record 185, epoch 5/5
Creating the dataset for record: 186
Training on record 186, epoch 1/5
Training on record 186, epoch 2/5
Training on record 186, epoch 3/5
Training on record 186, epoch 4/5
Training on record 186, epoch 5/5
Creating the dataset for record: 187
Training on record 187, epoch 1/5
Training on record 187, epoch 2/5
Training on record 187, epoch 3/5
Training on record 187, epoch 4/5
Training on record 187, epoch 5/5
Creating the dataset for record: 199
Training on record 199, epoch 1/5
Training on record 199, epoch 2/5
Training on record 199, epoch 3/5
Training on record 199, epoch 4/5
Training on record 199, epoch 5/5
Creating the dataset for record: 200
Training on record 200, epoch 1/5
Training on record 200, epoch 2/5
Training on record 200, epoch 3/5
Training on record 200, epoch 4/5
Training on record 200, epoch 5/5
Creating the dataset for record: 201
Training on record 201, epoch 1/5
Training on record 201, epoch 2/5
Training on record 201, epoch 3/5
Training on record 201, epoch 4/5
Training on record 201, epoch 5/5
Creating the dataset for record: 202
Training on record 202, epoch 1/5
Training on record 202, epoch 2/5
Training on record 202, epoch 3/5
Training on record 202, epoch 4/5
Training on record 202, epoch 5/5
Creating the dataset for record: 203
Training on record 203, epoch 1/5
Training on record 203, epoch 2/5
Training on record 203, epoch 3/5
Training on record 203, epoch 4/5
Training on record 203, epoch 5/5
Creating the dataset for record: 204
Training on record 204, epoch 1/5
Training on record 204, epoch 2/5
Training on record 204, epoch 3/5
Training on record 204, epoch 4/5
Training on record 204, epoch 5/5
Creating the dataset for record: 205
Training on record 205, epoch 1/5
Training on record 205, epoch 2/5
Training on record 205, epoch 3/5
Training on record 205, epoch 4/5
Training on record 205, epoch 5/5
Creating the dataset for record: 206
Training on record 206, epoch 1/5
Training on record 206, epoch 2/5
Training on record 206, epoch 3/5
Training on record 206, epoch 4/5
Training on record 206, epoch 5/5
Creating the dataset for record: 218
Training on record 218, epoch 1/5
Training on record 218, epoch 2/5
Training on record 218, epoch 3/5
Training on record 218, epoch 4/5
Training on record 218, epoch 5/5
Creating the dataset for record: 219
Training on record 219, epoch 1/5
Training on record 219, epoch 2/5
Training on record 219, epoch 3/5
Training on record 219, epoch 4/5
Training on record 219, epoch 5/5
Creating the dataset for record: 220
Training on record 220, epoch 1/5
Training on record 220, epoch 2/5
Training on record 220, epoch 3/5
Training on record 220, epoch 4/5
Training on record 220, epoch 5/5
Creating the dataset for record: 221
Training on record 221, epoch 1/5
Training on record 221, epoch 2/5
Training on record 221, epoch 3/5
Training on record 221, epoch 4/5
Training on record 221, epoch 5/5
Creating the dataset for record: 222
Training on record 222, epoch 1/5
Training on record 222, epoch 2/5
Training on record 222, epoch 3/5
Training on record 222, epoch 4/5
Training on record 222, epoch 5/5
Creating the dataset for record: 223
Training on record 223, epoch 1/5
Training on record 223, epoch 2/5
Training on record 223, epoch 3/5
Training on record 223, epoch 4/5
Training on record 223, epoch 5/5
Creating the dataset for record: 224
Training on record 224, epoch 1/5
Training on record 224, epoch 2/5
Training on record 224, epoch 3/5
Training on record 224, epoch 4/5
Training on record 224, epoch 5/5
Creating the dataset for record: 225
Training on record 225, epoch 1/5
Training on record 225, epoch 2/5
Training on record 225, epoch 3/5
Training on record 225, epoch 4/5
Training on record 225, epoch 5/5
Creating the dataset for record: 226
Training on record 226, epoch 1/5
Training on record 226, epoch 2/5
Training on record 226, epoch 3/5
Training on record 226, epoch 4/5
Training on record 226, epoch 5/5
Creating the dataset for record: 227
Training on record 227, epoch 1/5
Training on record 227, epoch 2/5
Training on record 227, epoch 3/5
Training on record 227, epoch 4/5
Training on record 227, epoch 5/5
Creating the dataset for record: 228
Training on record 228, epoch 1/5
Training on record 228, epoch 2/5
Training on record 228, epoch 3/5
Training on record 228, epoch 4/5
Training on record 228, epoch 5/5
Creating the dataset for record: 229
Training on record 229, epoch 1/5
Training on record 229, epoch 2/5
Training on record 229, epoch 3/5
Training on record 229, epoch 4/5
Training on record 229, epoch 5/5
Creating the dataset for record: 230
Training on record 230, epoch 1/5
Training on record 230, epoch 2/5
Training on record 230, epoch 3/5
Training on record 230, epoch 4/5
Training on record 230, epoch 5/5
Creating the dataset for record: 231
Training on record 231, epoch 1/5
Training on record 231, epoch 2/5
Training on record 231, epoch 3/5
Training on record 231, epoch 4/5
Training on record 231, epoch 5/5
Creating the dataset for record: 232
Training on record 232, epoch 1/5
Training on record 232, epoch 2/5
Training on record 232, epoch 3/5
Training on record 232, epoch 4/5
Training on record 232, epoch 5/5
Creating the dataset for record: 233
Training on record 233, epoch 1/5
Training on record 233, epoch 2/5
Training on record 233, epoch 3/5
Training on record 233, epoch 4/5
Training on record 233, epoch 5/5
Creating the dataset for record: 234
Training on record 234, epoch 1/5
Training on record 234, epoch 2/5
Training on record 234, epoch 3/5
Training on record 234, epoch 4/5
Training on record 234, epoch 5/5
Creating the dataset for record: 235
Training on record 235, epoch 1/5
Training on record 235, epoch 2/5
Training on record 235, epoch 3/5
Training on record 235, epoch 4/5
Training on record 235, epoch 5/5
Creating the dataset for record: 236
Training on record 236, epoch 1/5
Training on record 236, epoch 2/5
Training on record 236, epoch 3/5
Training on record 236, epoch 4/5
Training on record 236, epoch 5/5
Creating the dataset for record: 237
Training on record 237, epoch 1/5
Training on record 237, epoch 2/5
Training on record 237, epoch 3/5
Training on record 237, epoch 4/5
Training on record 237, epoch 5/5
Creating the dataset for record: 238
Training on record 238, epoch 1/5
Training on record 238, epoch 2/5
Training on record 238, epoch 3/5
Training on record 238, epoch 4/5
Training on record 238, epoch 5/5
Creating the dataset for record: 239
Training on record 239, epoch 1/5
Training on record 239, epoch 2/5
Training on record 239, epoch 3/5
Training on record 239, epoch 4/5
Training on record 239, epoch 5/5
Creating the dataset for record: 240
Training on record 240, epoch 1/5
Training on record 240, epoch 2/5
Training on record 240, epoch 3/5
Training on record 240, epoch 4/5
Training on record 240, epoch 5/5
Creating the dataset for record: 241
Training on record 241, epoch 1/5
Training on record 241, epoch 2/5
Training on record 241, epoch 3/5
Training on record 241, epoch 4/5
Training on record 241, epoch 5/5
Creating the dataset for record: 242
Training on record 242, epoch 1/5
Training on record 242, epoch 2/5
Training on record 242, epoch 3/5
Training on record 242, epoch 4/5
Training on record 242, epoch 5/5
Creating the dataset for record: 243
Training on record 243, epoch 1/5
Training on record 243, epoch 2/5
Training on record 243, epoch 3/5
Training on record 243, epoch 4/5
Training on record 243, epoch 5/5
Creating the dataset for record: 244
Training on record 244, epoch 1/5
Training on record 244, epoch 2/5
Training on record 244, epoch 3/5
Training on record 244, epoch 4/5
Training on record 244, epoch 5/5
Creating the dataset for record: 245
Training on record 245, epoch 1/5
Training on record 245, epoch 2/5
Training on record 245, epoch 3/5
Training on record 245, epoch 4/5
Training on record 245, epoch 5/5
Creating the dataset for record: 246
Training on record 246, epoch 1/5
Training on record 246, epoch 2/5
Training on record 246, epoch 3/5
Training on record 246, epoch 4/5
Training on record 246, epoch 5/5
Creating the dataset for record: 247
Training on record 247, epoch 1/5
Training on record 247, epoch 2/5
Training on record 247, epoch 3/5
Training on record 247, epoch 4/5
Training on record 247, epoch 5/5

# Test

In [6]:
import torch

model = TurnMovementClassifier(hidden_size=64, num_classes=3)
model.load_state_dict(torch.load("turn_movement_kian/turn_movement_model_record_931.pth"))
model.eval()

TurnMovementClassifier(
  (lstm): LSTM(1, 64, num_layers=2, batch_first=True, bidirectional=True)
  (attn): Linear(in_features=128, out_features=1, bias=True)
  (xy_mlp): Sequential(
    (0): Linear(in_features=2, out_features=16, bias=True)
    (1): ReLU()
    (2): Linear(in_features=16, out_features=16, bias=True)
  )
  (final_mlp): Sequential(
    (0): Linear(in_features=144, out_features=64, bias=True)
    (1): ReLU()
    (2): Linear(in_features=64, out_features=3, bias=True)
  )
)

In [15]:
record_id = 500
test_data = df[df["record_id"] == record_id]
print("Shape:", test_data.shape)
print("Number of vehicles", test_data["track_id"].nunique())

Shape: (187305, 15)
Number of vehicles 557

In [9]:
import pandas as pd
df = pd.read_csv("augmented_vehicle_movements.csv")

In [ ]:
import numpy as np
import torch

def extract_features_from_track(track_group):

    track_group = track_group.sort_values("time")

    x_c = ((track_group["x1"] + track_group["x2"]) / 2).values
    y_c = ((track_group["y1"] + track_group["y2"]) / 2).values

    dx = np.diff(x_c, prepend=x_c[0])
    dy = np.diff(y_c, prepend=y_c[0])

    start_heading = np.arctan2(dy[0], dx[0])
    end_heading   = np.arctan2(dy[-1], dx[-1])

    # stable heading difference
    delta = np.arctan2(
        np.sin(end_heading - start_heading),
        np.cos(end_heading - start_heading)
    )

    final_x = x_c[-1]
    final_y = y_c[-1]

    return torch.tensor([delta, final_x, final_y], dtype=torch.float32)
def predict_turn_movement(model, track_group, turn_movement_map):
    feature_vec = extract_features_from_track(track_group).unsqueeze(0)  # shape (1,3)
    logits = model(feature_vec)
    pred = torch.argmax(logits, dim=1).item()

    # reverse map: 0→10, 1→20, 2→30
    reverse_map = {v:k for k,v in turn_movement_map.items()}
    return reverse_map[pred]

turn_movement_map = {10:0, 20:1, 30:2}  # same used in training
vehicle_prediction = predict_turn_movement(model, some_track_df, turn_movement_map)
print("Predicted movement:", vehicle_prediction)

Sample 0: True Label = 1, Predicted Label = 0
Sample 1: True Label = 0, Predicted Label = 2
Sample 2: True Label = 1, Predicted Label = 1
Sample 3: True Label = 0, Predicted Label = 2
Sample 4: True Label = 0, Predicted Label = 0
Sample 5: True Label = 1, Predicted Label = 1
Sample 6: True Label = 1, Predicted Label = 1
Sample 7: True Label = 0, Predicted Label = 2
Sample 8: True Label = 1, Predicted Label = 1
Sample 9: True Label = 2, Predicted Label = 2
Sample 10: True Label = 2, Predicted Label = 2
Sample 11: True Label = 1, Predicted Label = 0
Sample 12: True Label = 0, Predicted Label = 2
Sample 13: True Label = 0, Predicted Label = 2
Sample 14: True Label = 0, Predicted Label = 2
Sample 15: True Label = 1, Predicted Label = 0
Sample 16: True Label = 0, Predicted Label = 2
Sample 17: True Label = 1, Predicted Label = 0
Sample 18: True Label = 0, Predicted Label = 2
Sample 19: True Label = 0, Predicted Label = 2
Sample 20: True Label = 0, Predicted Label = 2
Sample 21: True Label = 1, Predicted Label = 1
Sample 22: True Label = 0, Predicted Label = 2
Sample 23: True Label = 0, Predicted Label = 0
Sample 24: True Label = 0, Predicted Label = 2
Sample 25: True Label = 0, Predicted Label = 2
Sample 26: True Label = 0, Predicted Label = 0
Sample 27: True Label = 0, Predicted Label = 2
Sample 28: True Label = 0, Predicted Label = 2
Sample 29: True Label = 0, Predicted Label = 2
Sample 30: True Label = 0, Predicted Label = 2
Sample 31: True Label = 1, Predicted Label = 0
Sample 32: True Label = 1, Predicted Label = 0
Sample 33: True Label = 0, Predicted Label = 0
Sample 34: True Label = 1, Predicted Label = 0
Sample 35: True Label = 0, Predicted Label = 0
Sample 36: True Label = 1, Predicted Label = 1
Sample 37: True Label = 0, Predicted Label = 0
Sample 38: True Label = 0, Predicted Label = 1
Sample 39: True Label = 1, Predicted Label = 1
Sample 40: True Label = 0, Predicted Label = 0
Sample 41: True Label = 1, Predicted Label = 1
Sample 42: True Label = 1, Predicted Label = 1
Sample 43: True Label = 1, Predicted Label = 1
Sample 44: True Label = 0, Predicted Label = 2
Sample 45: True Label = 0, Predicted Label = 2
Sample 46: True Label = 0, Predicted Label = 2
Sample 47: True Label = 0, Predicted Label = 2
Sample 48: True Label = 1, Predicted Label = 0
Sample 49: True Label = 0, Predicted Label = 2
Sample 50: True Label = 0, Predicted Label = 2
Sample 51: True Label = 0, Predicted Label = 0
Sample 52: True Label = 0, Predicted Label = 0
Sample 53: True Label = 0, Predicted Label = 2
Sample 54: True Label = 0, Predicted Label = 0
Sample 55: True Label = 0, Predicted Label = 2
Sample 56: True Label = 0, Predicted Label = 2
Sample 57: True Label = 0, Predicted Label = 2
Sample 58: True Label = 2, Predicted Label = 0
Sample 59: True Label = 0, Predicted Label = 0
Sample 60: True Label = 0, Predicted Label = 2
Sample 61: True Label = 0, Predicted Label = 2
Sample 62: True Label = 1, Predicted Label = 0
Sample 63: True Label = 0, Predicted Label = 2
Sample 64: True Label = 0, Predicted Label = 2
Sample 65: True Label = 0, Predicted Label = 0
Sample 66: True Label = 1, Predicted Label = 0
Sample 67: True Label = 0, Predicted Label = 2
Sample 68: True Label = 0, Predicted Label = 2
Sample 69: True Label = 1, Predicted Label = 0
Sample 70: True Label = 0, Predicted Label = 2
Sample 71: True Label = 1, Predicted Label = 1
Sample 72: True Label = 0, Predicted Label = 0
Sample 73: True Label = 0, Predicted Label = 2
Sample 74: True Label = 1, Predicted Label = 0
Sample 75: True Label = 1, Predicted Label = 1
Sample 76: True Label = 0, Predicted Label = 0
Sample 77: True Label = 1, Predicted Label = 1
Sample 78: True Label = 1, Predicted Label = 1
Sample 79: True Label = 0, Predicted Label = 2
Sample 80: True Label = 0, Predicted Label = 2
Sample 81: True Label = 0, Predicted Label = 2
Sample 82: True Label = 0, Predicted Label = 2
Sample 83: True Label = 1, Predicted Label = 0
Sample 84: True Label = 1, Predicted Label = 1
Sample 85: True Label = 0, Predicted Label = 2
Sample 86: True Label = 1, Predicted Label = 0
Sample 87: True Label = 0, Predicted Label = 2
Sample 88: True Label = 0, Predicted Label = 2
Sample 89: True Label = 0, Predicted Label = 2
Sample 90: True Label = 0, Predicted Label = 2
Sample 91: True Label = 0, Predicted Label = 2
Sample 92: True Label = 0, Predicted Label = 2
Sample 93: True Label = 0, Predicted Label = 0
Sample 94: True Label = 0, Predicted Label = 2
Sample 95: True Label = 0, Predicted Label = 0
Sample 96: True Label = 0, Predicted Label = 2
Sample 97: True Label = 0, Predicted Label = 2
Sample 98: True Label = 0, Predicted Label = 0
Sample 99: True Label = 0, Predicted Label = 2
Sample 100: True Label = 1, Predicted Label = 0
Sample 101: True Label = 1, Predicted Label = 0
Sample 102: True Label = 0, Predicted Label = 2
Sample 103: True Label = 1, Predicted Label = 1
Sample 104: True Label = 1, Predicted Label = 1
Sample 105: True Label = 1, Predicted Label = 1
Sample 106: True Label = 1, Predicted Label = 1
Sample 107: True Label = 0, Predicted Label = 0
Sample 108: True Label = 0, Predicted Label = 2
Sample 109: True Label = 0, Predicted Label = 2
Sample 110: True Label = 0, Predicted Label = 2
Sample 111: True Label = 0, Predicted Label = 2
Sample 112: True Label = 0, Predicted Label = 2
Sample 113: True Label = 0, Predicted Label = 2
Sample 114: True Label = 0, Predicted Label = 0
Sample 115: True Label = 0, Predicted Label = 2
Sample 116: True Label = 0, Predicted Label = 2
Sample 117: True Label = 0, Predicted Label = 2
Sample 118: True Label = 0, Predicted Label = 2
Sample 119: True Label = 0, Predicted Label = 0
Sample 120: True Label = 1, Predicted Label = 1
Sample 121: True Label = 0, Predicted Label = 2
Sample 122: True Label = 0, Predicted Label = 2
Sample 123: True Label = 0, Predicted Label = 2
Sample 124: True Label = 0, Predicted Label = 2
Sample 125: True Label = 0, Predicted Label = 0
Sample 126: True Label = 0, Predicted Label = 2
Sample 127: True Label = 0, Predicted Label = 2
Sample 128: True Label = 1, Predicted Label = 1
Sample 129: True Label = 1, Predicted Label = 1
Sample 130: True Label = 1, Predicted Label = 1
Sample 131: True Label = 1, Predicted Label = 1
Sample 132: True Label = 1, Predicted Label = 1
Sample 133: True Label = 1, Predicted Label = 0
Sample 134: True Label = 1, Predicted Label = 1
Sample 135: True Label = 0, Predicted Label = 2
Sample 136: True Label = 1, Predicted Label = 0
Sample 137: True Label = 0, Predicted Label = 2
Sample 138: True Label = 1, Predicted Label = 0
Sample 139: True Label = 0, Predicted Label = 2
Sample 140: True Label = 0, Predicted Label = 2
Sample 141: True Label = 0, Predicted Label = 2
Sample 142: True Label = 0, Predicted Label = 2
Sample 143: True Label = 0, Predicted Label = 0
Sample 144: True Label = 0, Predicted Label = 2
Sample 145: True Label = 2, Predicted Label = 0
Sample 146: True Label = 0, Predicted Label = 2
Sample 147: True Label = 0, Predicted Label = 1
Sample 148: True Label = 0, Predicted Label = 2
Sample 149: True Label = 0, Predicted Label = 2
Sample 150: True Label = 0, Predicted Label = 2
Sample 151: True Label = 0, Predicted Label = 2
Sample 152: True Label = 0, Predicted Label = 1
Sample 153: True Label = 1, Predicted Label = 0
Sample 154: True Label = 1, Predicted Label = 0
Sample 155: True Label = 1, Predicted Label = 1
Sample 156: True Label = 1, Predicted Label = 1
Sample 157: True Label = 1, Predicted Label = 0
Sample 158: True Label = 1, Predicted Label = 0
Sample 159: True Label = 0, Predicted Label = 2
Sample 160: True Label = 0, Predicted Label = 2
Sample 161: True Label = 0, Predicted Label = 2
Sample 162: True Label = 1, Predicted Label = 1
Sample 163: True Label = 1, Predicted Label = 1
Sample 164: True Label = 0, Predicted Label = 2
Sample 165: True Label = 0, Predicted Label = 2
Sample 166: True Label = 0, Predicted Label = 2
Sample 167: True Label = 0, Predicted Label = 2
Sample 168: True Label = 0, Predicted Label = 0
Sample 169: True Label = 0, Predicted Label = 0
Sample 170: True Label = 0, Predicted Label = 2
Sample 171: True Label = 0, Predicted Label = 2
Sample 172: True Label = 0, Predicted Label = 2
Sample 173: True Label = 0, Predicted Label = 2
Sample 174: True Label = 0, Predicted Label = 2
Sample 175: True Label = 0, Predicted Label = 2
Sample 176: True Label = 0, Predicted Label = 1
Sample 177: True Label = 0, Predicted Label = 2
Sample 178: True Label = 0, Predicted Label = 2
Sample 179: True Label = 0, Predicted Label = 2
Sample 180: True Label = 1, Predicted Label = 0
Sample 181: True Label = 0, Predicted Label = 2
Sample 182: True Label = 0, Predicted Label = 1
Sample 183: True Label = 0, Predicted Label = 2
Sample 184: True Label = 0, Predicted Label = 2
Sample 185: True Label = 0, Predicted Label = 2
Sample 186: True Label = 0, Predicted Label = 2
Sample 187: True Label = 1, Predicted Label = 0
Sample 188: True Label = 1, Predicted Label = 1
Sample 189: True Label = 0, Predicted Label = 0
Sample 190: True Label = 1, Predicted Label = 1
Sample 191: True Label = 1, Predicted Label = 0
Sample 192: True Label = 1, Predicted Label = 0
Sample 193: True Label = 1, Predicted Label = 0
Sample 194: True Label = 1, Predicted Label = 0
Sample 195: True Label = 1, Predicted Label = 0
Sample 196: True Label = 0, Predicted Label = 2
Sample 197: True Label = 0, Predicted Label = 2
Sample 198: True Label = 1, Predicted Label = 0
Sample 199: True Label = 0, Predicted Label = 2
Sample 200: True Label = 0, Predicted Label = 2
Sample 201: True Label = 0, Predicted Label = 2
Sample 202: True Label = 0, Predicted Label = 0
Sample 203: True Label = 0, Predicted Label = 2
Sample 204: True Label = 0, Predicted Label = 2
Sample 205: True Label = 0, Predicted Label = 1
Sample 206: True Label = 0, Predicted Label = 0
Sample 207: True Label = 0, Predicted Label = 2
Sample 208: True Label = 0, Predicted Label = 2
Sample 209: True Label = 0, Predicted Label = 2
Sample 210: True Label = 0, Predicted Label = 0
Sample 211: True Label = 0, Predicted Label = 2
Sample 212: True Label = 0, Predicted Label = 2
Sample 213: True Label = 0, Predicted Label = 2
Sample 214: True Label = 0, Predicted Label = 2
Sample 215: True Label = 0, Predicted Label = 2
Sample 216: True Label = 0, Predicted Label = 2
Sample 217: True Label = 1, Predicted Label = 0
Sample 218: True Label = 0, Predicted Label = 2
Sample 219: True Label = 0, Predicted Label = 2
Sample 220: True Label = 0, Predicted Label = 2
Sample 221: True Label = 0, Predicted Label = 2
Sample 222: True Label = 0, Predicted Label = 2
Sample 223: True Label = 1, Predicted Label = 0
Sample 224: True Label = 0, Predicted Label = 2
Sample 225: True Label = 0, Predicted Label = 2
Sample 226: True Label = 0, Predicted Label = 0
Sample 227: True Label = 0, Predicted Label = 2
Sample 228: True Label = 1, Predicted Label = 0
Sample 229: True Label = 1, Predicted Label = 1
Sample 230: True Label = 1, Predicted Label = 1
Sample 231: True Label = 1, Predicted Label = 1
Sample 232: True Label = 1, Predicted Label = 1
Sample 233: True Label = 1, Predicted Label = 1
Sample 234: True Label = 1, Predicted Label = 1
Sample 235: True Label = 1, Predicted Label = 1
Sample 236: True Label = 1, Predicted Label = 0
Sample 237: True Label = 0, Predicted Label = 2
Sample 238: True Label = 0, Predicted Label = 2
Sample 239: True Label = 1, Predicted Label = 1
Sample 240: True Label = 0, Predicted Label = 2
Sample 241: True Label = 0, Predicted Label = 2
Sample 242: True Label = 0, Predicted Label = 0
Sample 243: True Label = 0, Predicted Label = 2
Sample 244: True Label = 0, Predicted Label = 0
Sample 245: True Label = 0, Predicted Label = 0
Sample 246: True Label = 0, Predicted Label = 2
Sample 247: True Label = 0, Predicted Label = 0
Sample 248: True Label = 0, Predicted Label = 2
Sample 249: True Label = 0, Predicted Label = 2
Sample 250: True Label = 0, Predicted Label = 2
Sample 251: True Label = 0, Predicted Label = 2
Sample 252: True Label = 0, Predicted Label = 2
Sample 253: True Label = 0, Predicted Label = 2
Sample 254: True Label = 0, Predicted Label = 2
Sample 255: True Label = 1, Predicted Label = 0
Sample 256: True Label = 0, Predicted Label = 2
Sample 257: True Label = 0, Predicted Label = 0
Sample 258: True Label = 0, Predicted Label = 2
Sample 259: True Label = 0, Predicted Label = 2
Sample 260: True Label = 1, Predicted Label = 0
Sample 261: True Label = 1, Predicted Label = 0
Sample 262: True Label = 0, Predicted Label = 2
Sample 263: True Label = 0, Predicted Label = 2
Sample 264: True Label = 1, Predicted Label = 1
Sample 265: True Label = 1, Predicted Label = 1
Sample 266: True Label = 0, Predicted Label = 0
Sample 267: True Label = 1, Predicted Label = 1
Sample 268: True Label = 1, Predicted Label = 0
Sample 269: True Label = 0, Predicted Label = 1
Sample 270: True Label = 0, Predicted Label = 2
Sample 271: True Label = 1, Predicted Label = 1
Sample 272: True Label = 1, Predicted Label = 1
Sample 273: True Label = 0, Predicted Label = 2
Sample 274: True Label = 0, Predicted Label = 2
Sample 275: True Label = 0, Predicted Label = 2
Sample 276: True Label = 0, Predicted Label = 2
Sample 277: True Label = 0, Predicted Label = 2
Sample 278: True Label = 1, Predicted Label = 0
Sample 279: True Label = 1, Predicted Label = 1
Sample 280: True Label = 0, Predicted Label = 2
Sample 281: True Label = 0, Predicted Label = 0
Sample 282: True Label = 1, Predicted Label = 1
Sample 283: True Label = 2, Predicted Label = 2
Sample 284: True Label = 1, Predicted Label = 1
Sample 285: True Label = 2, Predicted Label = 2
Sample 286: True Label = 0, Predicted Label = 2
Sample 287: True Label = 1, Predicted Label = 1
Sample 288: True Label = 1, Predicted Label = 0
Sample 289: True Label = 1, Predicted Label = 0
Sample 290: True Label = 0, Predicted Label = 2
Sample 291: True Label = 0, Predicted Label = 2
Sample 292: True Label = 0, Predicted Label = 2
Sample 293: True Label = 1, Predicted Label = 0
Sample 294: True Label = 0, Predicted Label = 2
Sample 295: True Label = 1, Predicted Label = 0
Sample 296: True Label = 0, Predicted Label = 2
Sample 297: True Label = 0, Predicted Label = 2
Sample 298: True Label = 0, Predicted Label = 2
Sample 299: True Label = 1, Predicted Label = 1
Sample 300: True Label = 0, Predicted Label = 2
Sample 301: True Label = 0, Predicted Label = 0
Sample 302: True Label = 0, Predicted Label = 2
Sample 303: True Label = 0, Predicted Label = 2
Sample 304: True Label = 0, Predicted Label = 0
Sample 305: True Label = 0, Predicted Label = 2
Sample 306: True Label = 0, Predicted Label = 0
Sample 307: True Label = 0, Predicted Label = 2
Sample 308: True Label = 0, Predicted Label = 2
Sample 309: True Label = 1, Predicted Label = 0
Sample 310: True Label = 1, Predicted Label = 0
Sample 311: True Label = 0, Predicted Label = 0
Sample 312: True Label = 0, Predicted Label = 0
Sample 313: True Label = 1, Predicted Label = 1
Sample 314: True Label = 0, Predicted Label = 0
Sample 315: True Label = 0, Predicted Label = 1
Sample 316: True Label = 1, Predicted Label = 0
Sample 317: True Label = 1, Predicted Label = 1
Sample 318: True Label = 1, Predicted Label = 1
Sample 319: True Label = 0, Predicted Label = 0
Sample 320: True Label = 1, Predicted Label = 1
Sample 321: True Label = 1, Predicted Label = 1
Sample 322: True Label = 0, Predicted Label = 2
Sample 323: True Label = 0, Predicted Label = 2
Sample 324: True Label = 0, Predicted Label = 2
Sample 325: True Label = 0, Predicted Label = 2
Sample 326: True Label = 1, Predicted Label = 0
Sample 327: True Label = 0, Predicted Label = 2
Sample 328: True Label = 0, Predicted Label = 2
Sample 329: True Label = 0, Predicted Label = 2
Sample 330: True Label = 0, Predicted Label = 0
Sample 331: True Label = 0, Predicted Label = 2
Sample 332: True Label = 0, Predicted Label = 0
Sample 333: True Label = 0, Predicted Label = 2
Sample 334: True Label = 0, Predicted Label = 2
Sample 335: True Label = 2, Predicted Label = 0
Sample 336: True Label = 0, Predicted Label = 2
Sample 337: True Label = 0, Predicted Label = 0
Sample 338: True Label = 0, Predicted Label = 2
Sample 339: True Label = 2, Predicted Label = 0
Sample 340: True Label = 0, Predicted Label = 2
Sample 341: True Label = 1, Predicted Label = 0
Sample 342: True Label = 0, Predicted Label = 2
Sample 343: True Label = 0, Predicted Label = 2
Sample 344: True Label = 1, Predicted Label = 0
Sample 345: True Label = 0, Predicted Label = 2
Sample 346: True Label = 0, Predicted Label = 2
Sample 347: True Label = 0, Predicted Label = 0
Sample 348: True Label = 0, Predicted Label = 2
Sample 349: True Label = 1, Predicted Label = 1
Sample 350: True Label = 0, Predicted Label = 0
Sample 351: True Label = 1, Predicted Label = 1
Sample 352: True Label = 1, Predicted Label = 0
Sample 353: True Label = 0, Predicted Label = 1
Sample 354: True Label = 1, Predicted Label = 1
Sample 355: True Label = 0, Predicted Label = 0
Sample 356: True Label = 1, Predicted Label = 1
Sample 357: True Label = 1, Predicted Label = 1
Sample 358: True Label = 0, Predicted Label = 2
Sample 359: True Label = 0, Predicted Label = 2
Sample 360: True Label = 0, Predicted Label = 2
Sample 361: True Label = 0, Predicted Label = 2
Sample 362: True Label = 1, Predicted Label = 1
Sample 363: True Label = 1, Predicted Label = 0
Sample 364: True Label = 0, Predicted Label = 2
Sample 365: True Label = 1, Predicted Label = 0
Sample 366: True Label = 0, Predicted Label = 2
Sample 367: True Label = 0, Predicted Label = 2
Sample 368: True Label = 0, Predicted Label = 2
Sample 369: True Label = 0, Predicted Label = 2
Sample 370: True Label = 0, Predicted Label = 2
Sample 371: True Label = 0, Predicted Label = 2
Sample 372: True Label = 0, Predicted Label = 0
Sample 373: True Label = 0, Predicted Label = 2
Sample 374: True Label = 0, Predicted Label = 2
Sample 375: True Label = 0, Predicted Label = 2
Sample 376: True Label = 0, Predicted Label = 2
Sample 377: True Label = 0, Predicted Label = 0
Sample 378: True Label = 0, Predicted Label = 2
Sample 379: True Label = 1, Predicted Label = 0
Sample 380: True Label = 1, Predicted Label = 0
Sample 381: True Label = 0, Predicted Label = 2
Sample 382: True Label = 1, Predicted Label = 0
Sample 383: True Label = 1, Predicted Label = 1
Sample 384: True Label = 1, Predicted Label = 1
Sample 385: True Label = 1, Predicted Label = 1
Sample 386: True Label = 0, Predicted Label = 0
Sample 387: True Label = 0, Predicted Label = 2
Sample 388: True Label = 0, Predicted Label = 2
Sample 389: True Label = 0, Predicted Label = 1
Sample 390: True Label = 0, Predicted Label = 2
Sample 391: True Label = 0, Predicted Label = 2
Sample 392: True Label = 1, Predicted Label = 0
Sample 393: True Label = 0, Predicted Label = 2
Sample 394: True Label = 0, Predicted Label = 2
Sample 395: True Label = 0, Predicted Label = 0
Sample 396: True Label = 0, Predicted Label = 2
Sample 397: True Label = 0, Predicted Label = 1
Sample 398: True Label = 0, Predicted Label = 2
Sample 399: True Label = 0, Predicted Label = 0
Sample 400: True Label = 0, Predicted Label = 0
Sample 401: True Label = 1, Predicted Label = 1
Sample 402: True Label = 0, Predicted Label = 2
Sample 403: True Label = 0, Predicted Label = 2
Sample 404: True Label = 0, Predicted Label = 2
Sample 405: True Label = 0, Predicted Label = 2
Sample 406: True Label = 1, Predicted Label = 0
Sample 407: True Label = 0, Predicted Label = 0
Sample 408: True Label = 0, Predicted Label = 2
Sample 409: True Label = 1, Predicted Label = 0
Sample 410: True Label = 0, Predicted Label = 2
Sample 411: True Label = 1, Predicted Label = 1
Sample 412: True Label = 1, Predicted Label = 1
Sample 413: True Label = 1, Predicted Label = 1
Sample 414: True Label = 0, Predicted Label = 2
Sample 415: True Label = 1, Predicted Label = 0
Sample 416: True Label = 1, Predicted Label = 0
Sample 417: True Label = 0, Predicted Label = 2